apiVersion: v1
kind: Service
metadata:
  name: dabdns
spec:
  selector:
    app: dabdns
  ports:
  - port: 5353
    targetPort: 5353
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dabdns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dabdns
  template:
    metadata:
      labels:
        app: dabdns
    spec:
      containers:
      - name: dabdns
        image: dabdns/dabdns
        resources:
          limits:
            memory: "32Mi"
            cpu: "100m"
        ports:
        - containerPort: 5353
