images:
- name: dabdns/dabdns
  newTag: latest
- name: powerdns/pdns-auth-master
  newTag: latest

configMapGenerator:
- name: powerdns-dabdns-config
  files:
  - config/powerdns/dabdns.conf
- name: dabdns-config
  files:
  - config/dabdns/dabdns.yaml

secretGenerator: []

resources:
- powerdns.yaml
- dabdns.yaml
